### ISSUE TITLE
Enhance Spring Cloud Example to configure datasource of the app

### ISSUE THREAD

**Issue by cmoulliard** [snowdrop/servicecatalog-connector#1]
Enhance Spring Cloud Example to configure datasource of the app

https://github.com/snowdrop/servicecatalog-connector/tree/master/examples/service-info-printer/src/main/java/me/snowdrop/servicecatalog/connector/examples

Do we have to develop within the cloud connector project logic needed to map Service's parameters with common bean that we could instantiate with Spring : DataSource, JMS Broker, ... ?

**Comment by iocanel** [comment]
For common service kinds like sql dbs etc. This is already implemented in to core connectors. For other service kinds we will have to implement it

**Comment by iocanel** [comment]
I think that this should be closed.
